[tool.poetry]
name = "moana"
version = "0.1.0"
description = "AI research project on example of the game engine"
authors = ["leovs09 <leovs010@gmail.com>"]
license = "GNU AGPLv3"
requires-python = ">=3.13,<4.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
